spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aitschool-spring?serverTimezone=UTC
    username: root
    password: 123456
  flyway:
    locations: "classpath:db/migration"
    validate-on-migrate: false
    encoding: UTF-8
    out-of-order: true
